### ISSUE TITLE
crates/stark/src/oods.rs:31:18: attempt to subtract with overflow

### ISSUE THREAD

**Issue by tdelabro** [iosis-tech/swiftness#55]
I changed my `cpu_air_params.json` to `"fri_step_list": [0, 4, 4, 4, 4]"` and it now crashes later in the verification:
At `crates/stark/src/oods.rs:31:18` which is:
```rust
pub fn verify_oods<Layout: LayoutTrait>(
    oods: &[Felt],
    interaction_elements: &Layout::InteractionElements,
    public_input: &PublicInput,
    constraint_coefficients: &[Felt],
    oods_point: &Felt,
    trace_domain_size: &Felt,
    trace_generator: &Felt,
) -> Result<(), OodsVerifyError> {
    let composition_from_trace = Layout::eval_composition_polynomial(
        interaction_elements,
        public_input,
        &oods[0..oods.len() - 2], // < here
        constraint_coefficients,
        oods_point,
        trace_domain_size,
        trace_generator,
    )?;
    ...
}
```

_Originally posted by @tdelabro in https://github.com/iosis-tech/swiftness/issues/54#issuecomment-2551470208_

**Comment by tdelabro** [comment]
Could it be that my annotations look like that:
```json
		"V->P: /cpu air/STARK/Out Of Domain Sampling/OODS values: Evaluation point: Field Element(0x6554169f2c8b8fa0f8b0c2f65af48039f64ad47f2fd90caaa2bb808f600f829)",
		"P->V[96:128]: /cpu air/STARK/Out Of Domain Sampling/OODS values: 0: Field Element(0x40536e9e9158351e084b9ec5f9831c96969e4efd8f0b56f8532f377d2988483)",
		"P->V[128:160]: /cpu air/STARK/Out Of Domain Sampling/OODS values: 1: Field Element(0x369e29b182cf9accf1868d724708ba83a462c4c8fa425d0c9d5c956a43ec75a)",
		"P->V[160:192]: /cpu air/STARK/Out Of Domain Sampling/OODS values: 2: Field Element(0x2e553a9831fa0df8fa5d1029d152a7dcda95c310aa6bd5a9fe5b650abce5078)",
		"P->V[192:224]: /cpu air/STARK/Out Of Domain Sampling/OODS values: 3: Field Element(0x1f179c246f2d0347d1cad76a75781ef805854f85b3fe933c5179a0131a6b0d6)",
```

while your code expect the `odds` prefix to be `"STARK/Out Of Domain Sampling/OODS values"`
see `proof_parser/src/annotations/annotation_kind.rs`
```rust
            Annotation::OodsValues => PrefixAndKind {
                prefix: "STARK/Out Of Domain Sampling/OODS values".to_string(),
                kinds: AnnotationKinds::FieldElements,
            },
```

**Comment by tdelabro** [comment]
Yup, I think something is wrong in the parsing because I printed my `oods`:
```rust
    let x = stark_proof.unsent_commitment.oods_values;
    panic!("{:?}", x);
 ```
 and go `[]`

**Comment by Okm165** [comment]
do u have latet stone built? 
i am asking this Q latest stone is annotating oods values like this
https://github.com/iosis-tech/swiftness/blob/main/examples/proofs/recursive/cairo0_stone5_example_proof.json#L16

**Comment by Okm165** [comment]
Oh It is not version issue latest [Stone v3](https://github.com/starkware-libs/stone-prover/tree/1414a545e4fb38a85391289abe91dd4467d268e1) is fine
What u are missing is the correct proof params especially `"verifier_friendly_channel_updates" : true`
Take a look at the proof params in the repo guide: https://github.com/iosis-tech/swiftness/blob/main/examples/proofs/cpu_air_params.json

**Comment by tdelabro** [comment]
Mine is currently:
```
{
    "field": "PrimeField0",
    "stark": {
        "fri": {
            "fri_step_list": [
                0,
                4,
                4,
                4,
                4
            ],
            "last_layer_degree_bound": 32,
            "n_queries": 18,
            "proof_of_work_bits": 30
        },
        "log_n_cosets": 4
    },
    "use_extension_field": false
}
```
What else should I change?

**Comment by Okm165** [comment]
Just copy json from my link and adjust fri layers for ur case

**Comment by tdelabro** [comment]
So this is the only configuration verifiable with `swiftness`, or is there some room for configuration here?

**Comment by tdelabro** [comment]
should `n_verifier_friendly_commitment_layers` be equal to the sum of `fri_step_list`?

I tried it (setting it to 14 while keeping the last config I showed) and it failed

**Comment by Okm165** [comment]
this command should verify proof with above configuration
```cargo run --release --bin swiftness --features starknet,blake2s_248_lsb,stone6 --no-default-features -- --proof your_proof.json```

**Comment by Okm165** [comment]
Given the correctly generated proof the verifier fails to verify with error ```Error: PublicInputError(MaxSteps)```
This is due to this check failing https://github.com/iosis-tech/swiftness/blob/main/crates/air/src/layout/starknet/mod.rs#L525
